const vehiculos = [
    {
        id: 0,
        imagen:"imagenes/ToyotaCamry.jpg",
        nombre: "Camry HV 2.5 eCVT",
        marca: "Toyota",
        descripcion: "2022 | 2.000km | La Plata, Buenos aires",
        precio: 5200000,

    },
    {
        id:1,
        imagen: "imagenes/Honda hrv.jpg",
        nombre: "HRV EX CVT",
        marca: "Honda",
        descripcion: "2021 | 1.250km | Capital Federal",
        precio: 4065000,

    },
    {
        id:2,
        imagen: "imagenes/peugot 208.jpg",
        nombre: "208 GT TIPCTRONIC",
        marca: "Peugeot",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 2500000,

    },
    {
        id:3,
        imagen:"imagenes/ford territory.jpg",
        nombre:"Territory TITANIUM",
        marca: "Ford",
        descripcion:"2022 | Okm | La Plata, Buenos Aires",
        precio: 6530000,
    },
    {
        id:4,
        imagen: "imagenes/toyotaSW4.jpg",
        nombre: "SW4 GR-S ",
        marca: "Toyota",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 11000000,
    },
    {
        id:5,
        imagen: "imagenes/Toyota Corolla.jpg",
        nombre: "Corolla GR-SPORT",
        marca: "Toyota",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 4000000,
    },
    {
        id:6,
        imagen: "imagenes/toxotaHillux.png",
        nombre: "Hillux 4x4 TDI AT",
        marca: "Toyota",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 8000000,
    },
    {
        id:7,
        imagen: "imagenes/308THIP.png",
        nombre: "308 THP TIPTRONIC",
        marca: "Peugeot",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 4000000,
    },
    {
        id:8,
        imagen: "imagenes/fordBronco.png",
        nombre: "Bronco Sport",
        marca: "Ford",
        descripcion: "2021 | 5.000km | Capital Federal",
        precio: 7500000,
    },
    {
        id:9,
        imagen: "imagenes/fordKuga.png",
        nombre: "Kuga Hibrida",
        marca: "Ford",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 10500000,
    },
    {
        id:10,
        imagen: "imagenes/rangerRaptor.png",
        nombre: "Ranger Raptor",
        marca: "Ford",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 9000000,
    },
    {
        id:11,
        imagen: "imagenes/f150.png",
        nombre: "Ford F-150 Hibrida",
        marca: "Ford",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 4000000,
    },
    {
        id:12,
        imagen: "imagenes/mustangMarch.png",
        nombre: "Mustang Mach 1",
        marca: "Ford",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 11608435,
    },
    {
        id:14,
        imagen: "imagenes/cruize.png",
        nombre: "Cruize Premier",
        marca: "Chevrolet",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 4000000,
    },
    {
        id:15,
        imagen: "imagenes/s10.png",
        nombre: "S10 High Country",
        marca: "Chevrolet",
        descripcion: "2022 | 0km | Capital Federal",
        precio: 6500435,
    },
]
